const {
  adminLearnerSummarySchema,
  instructorApprovalQueueItemSchema,
  instructorApprovalQueueResponseSchema,
  reconciliationQueueItemSchema,
  reconciliationQueueResponseSchema,
  reconciliationQueueStatusSchema,
} = require("./admin")
const {
  authenticatedSessionSchema,
  authSessionResponseSchema,
  authSessionSchema,
  loginPasswordSchema,
  localLoginRequestSchema,
  signedOutSessionSchema,
} = require("./auth")
const {
  catalogCourseListResponseSchema,
  catalogCourseSchema,
  catalogLevelSchema,
  catalogPriceMajorSchema,
  catalogQueryOpenApiSchema,
  catalogSortSchema,
} = require("./catalog")
const {
  checkoutOrderResponseSchema,
  checkoutOrderSchema,
  checkoutPolicySchema,
  checkoutRequestSchema,
  learnerPurchaseSchema,
  purchaseFinancialsSchema,
  purchaseLineItemSchema,
  purchaseStatusSchema,
  reconciliationResolutionSchema,
  refundProviderStatusSchema,
  refundRequestSchema,
} = require("./commerce")
const {
  amountMinorSchema,
  currencySchema,
  httpUrlSchema,
  idempotencyKeySchema,
  isoDateSchema,
  isoDateTimeSchema,
  minorMoneySchema,
  objectIdSchema,
  percentageSchema,
  policyVersionSchema,
  positiveAmountMinorSchema,
  positiveMinorMoneySchema,
  requestIdSchema,
} = require("./common")
const {
  canonicalLanguageCodeSchema,
  courseCategorySchema,
  courseDetailSchema,
  courseIdParamsSchema,
  courseLevelSchema,
  courseLifecycleStatusSchema,
  courseRatingSummarySchema,
  curriculumSectionSchema,
  lessonPreviewSchema,
} = require("./courses")
const {
  apiErrorDetailsSchema,
  apiErrorResponseSchema,
  apiErrorSchema,
  validationErrorDetailsSchema,
  validationIssueSchema,
} = require("./errors")
const {
  courseProgressSchema,
  lessonPlaybackSchema,
  progressUpdateRequestSchema,
} = require("./learning")
const {
  cursorPageInfoSchema,
  cursorPaginationOpenApiSchema,
  offsetPageInfoSchema,
  offsetPaginationOpenApiSchema,
  opaqueCursorSchema,
  resourceIdParamsSchema,
} = require("./pagination")
const {
  createReviewRequestSchema,
  publicReviewSchema,
  ratingSchema,
} = require("./reviews")
const {
  accountTypeSchema,
  authProviderSchema,
  authProvidersSchema,
  genderSchema,
  instructorApprovalStatusSchema,
  profileDetailsSchema,
  publicInstructorSchema,
  userIdentitySchema,
  userProfileSchema,
} = require("./users")

const contractSchemas = Object.freeze({
  RequestId: requestIdSchema,
  ObjectId: objectIdSchema,
  IsoDate: isoDateSchema,
  IsoDateTime: isoDateTimeSchema,
  Currency: currencySchema,
  AmountMinor: amountMinorSchema,
  PositiveAmountMinor: positiveAmountMinorSchema,
  MinorMoney: minorMoneySchema,
  PositiveMinorMoney: positiveMinorMoneySchema,
  IdempotencyKey: idempotencyKeySchema,
  HttpUrl: httpUrlSchema,
  Percentage: percentageSchema,
  PolicyVersion: policyVersionSchema,
  OpaqueCursor: opaqueCursorSchema,
  CursorPageInfo: cursorPageInfoSchema,
  OffsetPageInfo: offsetPageInfoSchema,
  CursorPaginationQuery: cursorPaginationOpenApiSchema,
  OffsetPaginationQuery: offsetPaginationOpenApiSchema,
  ResourceIdParams: resourceIdParamsSchema,
  ApiErrorDetails: apiErrorDetailsSchema,
  ApiError: apiErrorSchema,
  ApiErrorResponse: apiErrorResponseSchema,
  ValidationIssue: validationIssueSchema,
  ValidationErrorDetails: validationErrorDetailsSchema,
  LoginPassword: loginPasswordSchema,
  LocalLoginRequest: localLoginRequestSchema,
  AuthenticatedSession: authenticatedSessionSchema,
  SignedOutSession: signedOutSessionSchema,
  AuthSession: authSessionSchema,
  AuthSessionResponse: authSessionResponseSchema,
  AccountType: accountTypeSchema,
  AuthProvider: authProviderSchema,
  AuthProviders: authProvidersSchema,
  Gender: genderSchema,
  InstructorApprovalStatus: instructorApprovalStatusSchema,
  UserIdentity: userIdentitySchema,
  UserProfile: userProfileSchema,
  ProfileDetails: profileDetailsSchema,
  PublicInstructor: publicInstructorSchema,
  CourseIdParams: courseIdParamsSchema,
  CanonicalLanguageCode: canonicalLanguageCodeSchema,
  CourseLevel: courseLevelSchema,
  CourseLifecycleStatus: courseLifecycleStatusSchema,
  CourseCategory: courseCategorySchema,
  CourseRatingSummary: courseRatingSummarySchema,
  LessonPreview: lessonPreviewSchema,
  CurriculumSection: curriculumSectionSchema,
  CourseDetail: courseDetailSchema,
  CatalogLevel: catalogLevelSchema,
  CatalogSort: catalogSortSchema,
  CatalogCourseListQuery: catalogQueryOpenApiSchema,
  CatalogPriceMajor: catalogPriceMajorSchema,
  CatalogCourse: catalogCourseSchema,
  CatalogCourseListResponse: catalogCourseListResponseSchema,
  ProgressUpdateRequest: progressUpdateRequestSchema,
  CourseProgress: courseProgressSchema,
  LessonPlayback: lessonPlaybackSchema,
  CreateReviewRequest: createReviewRequestSchema,
  PublicReview: publicReviewSchema,
  CheckoutPolicy: checkoutPolicySchema,
  CheckoutRequest: checkoutRequestSchema,
  CheckoutOrder: checkoutOrderSchema,
  CheckoutOrderResponse: checkoutOrderResponseSchema,
  PurchaseLineItem: purchaseLineItemSchema,
  PurchaseFinancials: purchaseFinancialsSchema,
  PurchaseStatus: purchaseStatusSchema,
  RefundProviderStatus: refundProviderStatusSchema,
  ReconciliationResolution: reconciliationResolutionSchema,
  LearnerPurchase: learnerPurchaseSchema,
  RefundRequest: refundRequestSchema,
  Rating: ratingSchema,
  AdminLearnerSummary: adminLearnerSummarySchema,
  ReconciliationQueueStatus: reconciliationQueueStatusSchema,
  InstructorApprovalQueueItem: instructorApprovalQueueItemSchema,
  InstructorApprovalQueueResponse: instructorApprovalQueueResponseSchema,
  ReconciliationQueueItem: reconciliationQueueItemSchema,
  ReconciliationQueueResponse: reconciliationQueueResponseSchema,
})

module.exports = { contractSchemas }
